name: Run AI Model Hourly and Commit signals.json

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:     # allows manual triggering

jobs:
  run-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run model.py
        run: python model.py

      - name: Commit and push signals.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add signals.json
          git commit -m "Update signals.json [auto]" || echo "No changes to commit"
          git push
